image:
  file: .gitpod.Dockerfile

tasks:
  - init: sudo yum install mysql-server 
    command: 'pip3 install beautifulsoup4 && pip3 install requests && pip3 install lxml && pip3 install mysql-connector-python '
